### PR TITLE
Fix #5545

### LINKED ISSUE #5545: BitmapText from atlas doesn't display properly with canvas renderer
## Version
Phaser 3.52 and newer

## Description
I use the technique when I combine bitmap font texture with atlas to reduce draw calls and improve performance. It stopped working since the commit https://github.com/photonstorm/phaser/commit/9116eddf99c40d236c6af628894b223ee3531ed6

## Example Test Code
https://codesandbox.io/s/laughing-framework-44p38?file=/index.ts

## Additional Information
This example also doesn't work if you will change renderer (line 37) to Canvas - http://labs.phaser.io/edit.html?src=src%5Cgame%20objects%5Cbitmaptext%5Cstatic%5Cbitmaptext-atlas.js

### PR DESCRIPTION
**Pull request by vforsh**
This PR (delete as applicable)

* Fixes a bug

Describe the changes below:
Fixes #5545 ("BitmapText from atlas doesn't display properly with canvas renderer")

### CODE REVIEW

File: src/gameobjects/bitmaptext/static/BitmapText.js [hunk 1]
```diff
@@ -264,6 +264,15 @@ var BitmapText = new Class({
          */
         this.dropShadowAlpha = 0.5;
 
+        /**
+         * Indicates whether the font texture is from an atlas or not.
+         *
+         * @name Phaser.GameObjects.BitmapText#fromAtlas
+         * @type {boolean}
+         * @since 3.53.2
```
Comment (vforsh) [inline src/gameobjects/bitmaptext/static/BitmapText.js:272]: I not sure what the next version will be so I put 3.53.2 here

**Comment by photonstorm** [comment]
👍
